## Multiclass Classification using Logistic Regression with iris datset

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [9]:
plt.gray()
dir(iris)
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

<Figure size 432x288 with 0 Axes>

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.2)
X_train

array([[4.9, 3. , 1.4, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [6. , 3. , 4.8, 1.8],
       [4.4, 3.2, 1.3, 0.2],
       [6.5, 3. , 5.5, 1.8],
       [5.5, 3.5, 1.3, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [7.2, 3.2, 6. , 1.8],
       [5. , 3.2, 1.2, 0.2],
       [6.4, 2.8, 5.6, 2.1],
       [6.3, 3.3, 6. , 2.5],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [7.1, 3. , 5.9, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.2, 2.7, 3.9, 1.4],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3. , 1.3, 0.2],
       [5.4, 3. , 4.5, 1.5],
       [5.1, 3.8, 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [6.1, 2.6, 5.6, 1.4],
       [5. , 3.5, 1.6, 0.6],
       [6.7, 3.3, 5.7, 2.1],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.8, 4.1, 1.3],
       [4.4, 2.9, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [7.2, 3.6, 6.1, 2.5],
       [4.9, 3.6, 1.4, 0.1],
       [5.8, 2.8, 5.1, 2.4],
       [6.2, 3

In [13]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver = "newton-cg", multi_class="auto")
model.fit(X_train, y_train)

LogisticRegression(solver='newton-cg')

In [16]:
model.score(X_train, y_train)

0.975

In [14]:
model.predict(X_test)

array([0, 2, 2, 0, 2, 2, 1, 0, 1, 1, 1, 1, 2, 0, 2, 0, 0, 1, 2, 1, 2, 2,
       0, 1, 2, 1, 1, 2, 2, 0])

In [15]:
model.score(X_test, y_test)

0.9666666666666667

In [19]:
iris.target[4]

0

In [21]:
model.predict([iris.data[4]])

array([0])